
  Performance statistics for DSP solver: icalls =      1

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =            5487
     no. of nonzeroes in lower triangle of a =          183099
     no. of nonzeroes in the factor l        =          849317
     ratio of nonzeroes in factor (min/max)  =          0.4350
     number of super nodes                   =             194
     maximum order of a front matrix         =             378
     maximum size of a front matrix          =           71631
     maximum size of a front trapezoid       =           35046
     no. of floating point ops for factor    =      1.3854D+08
     no. of floating point ops for solve     =      3.0536D+06
     ratio of flops for factor (min/max)     =          0.4678
     ratio of allocated memory (max/min)     =          1.8277
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               6
     number of threads per process used      =               1
     number of cores used                    =               6
     GPU acceleration activated
     percentage of GPU accelerated flops     =          0.0000
     time (cpu & wall) for structure input   =        0.000000        0.001517
     time (cpu & wall) for ordering          =        0.000000        0.010467
     time (cpu & wall) for other matrix prep =        0.078125        0.020186
     time (cpu & wall) for value input       =        0.000000        0.001348
     time (cpu & wall) for matrix distrib.   =        0.015625        0.016520
     time (cpu & wall) for numeric factor    =        0.015625        0.052588
     computational rate (gflops) for factor  =        8.866325        2.634372
     time (cpu & wall) for numeric solve     =        0.015625        0.019974
     computational rate (gflops) for solve   =        0.195431        0.152878
     effective I/O rate (GB/sec) for solve   =        0.728097        0.569560

     no input or output performed

  Solver Memory allocated on core    0       =        2.818 MB
  Solver Memory allocated on core    1       =        2.583 MB
  Solver Memory allocated on core    2       =        3.244 MB
  Solver Memory allocated on core    3       =        2.411 MB
  Solver Memory allocated on core    4       =        2.023 MB
  Solver Memory allocated on core    5       =        3.698 MB
  Total Solver Memory allocated by all cores =       16.778 MB

